version: '3.4'

services:

  rabbitMq:

    image: rabbitmq:3-management

    container_name: some-rabbit

    hostname: "my-rabbit"

    ports:
      - "15672:15672"
      - "5672:5672"

    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
 
    environment:
     - RABBITMQ_DEFAULT_USER = admin
     - RABBITMQ_DEFAULT_PASS = passw123
 
    restart: always
